const a = [
  {
    handle: "P001",
    displayName: "Nguyễn Văn An",
    gender: 1,
    birthYear: 1920,
    deathYear: 1995,
    generation: 1,
    isLiving: false,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: ["F001"],
    parentFamilies: [],
  },
  {
    handle: "P013",
    displayName: "Trần Thị Lan",
    gender: 2,
    birthYear: 1925,
    deathYear: 2000,
    generation: 1,
    isLiving: false,
    isPrivacyFiltered: false,
    isPatrilineal: false,
    families: [],
    parentFamilies: [],
  },
  {
    handle: "P016",
    displayName: "Trần Thị Lan B",
    gender: 2,
    birthYear: 1930,
    deathYear: null,
    generation: 1,
    isLiving: false,
    isPrivacyFiltered: false,
    isPatrilineal: false,
    families: [],
    parentFamilies: [],
  },
  {
    handle: "P002",
    displayName: "Nguyễn Văn Bình",
    gender: 1,
    birthYear: 1945,
    deathYear: null,
    generation: 2,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: ["F002", "F020", "F021"],
    parentFamilies: ["F001"],
  },
  {
    handle: "P003",
    displayName: "Nguyễn Văn Cường",
    gender: 1,
    birthYear: 1948,
    deathYear: null,
    generation: 2,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: ["F003"],
    parentFamilies: ["F001"],
  },
  {
    handle: "P004",
    displayName: "Nguyễn Văn Dũng",
    gender: 1,
    birthYear: 1951,
    deathYear: 2020,
    generation: 2,
    isLiving: false,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: ["F004"],
    parentFamilies: ["F001"],
  },
  {
    handle: "P014",
    displayName: "Lê Thị Mai",
    gender: 2,
    birthYear: 1948,
    deathYear: null,
    generation: 2,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: false,
    families: [],
    parentFamilies: [],
  },
  {
    handle: "P020",
    displayName: "Lê Thị Mai B",
    gender: 2,
    birthYear: 1948,
    deathYear: null,
    generation: 2,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: false,
    families: [],
    parentFamilies: [],
  },
  {
    handle: "P005",
    displayName: "Nguyễn Văn Hải",
    gender: 1,
    birthYear: 1970,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: ["F005"],
    parentFamilies: ["F002"],
  },
  {
    handle: "P006",
    displayName: "Nguyễn Văn Hùng",
    gender: 1,
    birthYear: 1973,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F002"],
  },
  {
    handle: "P007",
    displayName: "Nguyễn Văn Khoa",
    gender: 1,
    birthYear: 1975,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: ["F006"],
    parentFamilies: ["F003"],
  },
  {
    handle: "P008",
    displayName: "Nguyễn Văn Khánh",
    gender: 1,
    birthYear: 1978,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F003"],
  },
  {
    handle: "P009",
    displayName: "Nguyễn Văn Long",
    gender: 1,
    birthYear: 1980,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F004"],
  },
  {
    handle: "P015",
    displayName: "Phạm Thị Hoa",
    gender: 2,
    birthYear: 1972,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: false,
    families: [],
    parentFamilies: [],
  },
  {
    handle: "P021",
    displayName: "Nguyễn Văn Bình Con",
    gender: 1,
    birthYear: 1980,
    deathYear: null,
    generation: 3,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F021"],
  },
  {
    handle: "P010",
    displayName: "Nguyễn Văn Minh",
    gender: 1,
    birthYear: 1995,
    deathYear: null,
    generation: 4,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F005"],
  },
  {
    handle: "P011",
    displayName: "Nguyễn Văn Nam",
    gender: 1,
    birthYear: 1998,
    deathYear: null,
    generation: 4,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F005"],
  },
  {
    handle: "P012",
    displayName: "Nguyễn Văn Phúc",
    gender: 1,
    birthYear: 2000,
    deathYear: null,
    generation: 4,
    isLiving: true,
    isPrivacyFiltered: false,
    isPatrilineal: true,
    families: [],
    parentFamilies: ["F006"],
  },
];
